#include "common.hpp"

std::string g_RESOURCE_LOC = "./resources/";
std::default_random_engine g_RANDOM_TWISTER ((std::random_device())());

float g_TIME = 0;

float g_PARAM_SAMPLE_TIMESTEP = 1.0f / 60.0f;
int g_PARAM_OCTAVE_MIN_CLIP = 0;
int g_PARAM_OCTAVE_MAX_CLIP = 6;
int g_PARAM_SAMPLE_WIDTH = 8192;

float g_PARAM_NOTE_INTENSITY_ACCUMULATION = 0.5f;

float g_PARAM_TRIGGER_THRESHOLD = /*0.0315f*/2.2f /* (16384.0f / g_PARAM_SAMPLE_WIDTH)*/;
int g_PARAM_NOTESET_SIMILARITY_TOLERANCE_BUILD = 0;
int g_PARAM_NOTESET_SIMILARITY_TOLERANCE_RUNTIME = 0;

int g_PARAM_NOTESET_SIMILARITY_TOLERANCE = g_PARAM_NOTESET_SIMILARITY_TOLERANCE_BUILD;
